apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    jmx-prometheus-exporter: 'true'
  name: prf-mtc
  namespace: prf-mtc
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    port: metrics
    scheme: http
  namespaceSelector:
    any: true  
  selector:
    matchLabels:
      jmx-prometheus-exporter: 'true'
